variables:
  MAVEN_OPTS: >-
    -Dhttps.protocols=TLSv1.2
    -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository
    -Dorg.slf4j.simpleLogger.showDateTime=true
    -Djava.awt.headless=true

  MAVEN_CLI_OPTS: >-
    --batch-mode
    --errors
    --fail-at-end
    --show-version
    --no-transfer-progress
    -DinstallAtEnd=true
    -DdeployAtEnd=true

  SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
  GIT_DEPTH: "0"
  GIT_SUBMODULE_STRATEGY: recursive
  GIT_SUBMODULE_FORCE_HTTPS: "true"

image: $DOCKER_MIRROR_URL/library/maven:3-eclipse-temurin-21

include:
  - project: "appframework/gitlab-pipelines"
    ref: "main"
    file: "/steps/maven-compile.yml"
  - project: "appframework/gitlab-pipelines"
    ref: "main"
    file: "/steps/maven-sonar.yml"
  - project: "appframework/gitlab-pipelines"
    ref: "main"
    file: "/steps/git-commit.yml"

stages:
  - build
  - sast
  - transpile

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - .m2/repository/
    - target/
    - java/target/
    - transpiler/target/
    - parser/target/
    - .sonar/cache

compile:
  stage: build
  extends:
    - .step-maven-compile
  script:
  - mvn $MAVEN_CLI_OPTS clean package -DskipTests
  artifacts:
    paths:
    - transpiler/target/libldt3-transpiler-*.jar

sonarcloud-check:
  stage: sast
  needs:
    - compile
  extends:
    - .step-maven-sonar

transpile:
  stage: transpile
  needs:
    - compile
  script: java -jar transpiler/target/libldt3-transpiler-*.jar
  artifacts:
    paths:
    - rust/src
    - cs

commit:
  stage: transpile
  needs:
    - transpile
  variables:
    GIT_ADD_FILES: cs rust/src
  extends:
    - .step-git-commit
